
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.0.0
 * Query Engine version: 0c19ccc313cf9911a90d99d2ac2eb0280c76c513
 */
Prisma.prismaVersion = {
  client: "7.0.0",
  engine: "0c19ccc313cf9911a90d99d2ac2eb0280c76c513"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  twoFactorEnabled: 'twoFactorEnabled',
  username: 'username',
  displayUsername: 'displayUsername',
  role: 'role',
  banned: 'banned',
  banReason: 'banReason',
  banExpires: 'banExpires'
};

exports.Prisma.UserDetailsScalarFieldEnum = {
  id: 'id',
  dateOfBirth: 'dateOfBirth',
  street: 'street',
  apartmentNumber: 'apartmentNumber',
  city: 'city',
  postalCode: 'postalCode',
  phoneNumber: 'phoneNumber',
  daikinCoins: 'daikinCoins',
  userId: 'userId'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  expiresAt: 'expiresAt',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TwoFactorScalarFieldEnum = {
  id: 'id',
  secret: 'secret',
  backupCodes: 'backupCodes',
  userId: 'userId'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  customerEmail: 'customerEmail',
  dateOfPurchase: 'dateOfPurchase',
  nextDateOfService: 'nextDateOfService',
  totalPrice: 'totalPrice',
  daikinCoins: 'daikinCoins',
  notificationSent30Days: 'notificationSent30Days',
  notificationSent7Days: 'notificationSent7Days',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderProductScalarFieldEnum = {
  id: 'id',
  productSlug: 'productSlug',
  warranty: 'warranty',
  quantity: 'quantity',
  totalPrice: 'totalPrice',
  orderId: 'orderId'
};

exports.Prisma.BenefitDescriptionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  daikinCoins: 'daikinCoins',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isActive: 'isActive'
};

exports.Prisma.BenefitsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  redeemedAt: 'redeemedAt',
  comment: 'comment',
  benefitDescriptionId: 'benefitDescriptionId'
};

exports.Prisma.ServiceScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  dateOfProposedService: 'dateOfProposedService',
  dateOfService: 'dateOfService',
  serviceDetails: 'serviceDetails',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isActive: 'isActive'
};

exports.Prisma.CategoryTranslationScalarFieldEnum = {
  id: 'id',
  categorySlug: 'categorySlug',
  locale: 'locale',
  name: 'name',
  isActive: 'isActive'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  price: 'price',
  articleId: 'articleId',
  categorySlug: 'categorySlug',
  slug: 'slug',
  energyClass: 'energyClass',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductSpecsScalarFieldEnum = {
  id: 'id',
  productSlug: 'productSlug',
  locale: 'locale',
  title: 'title',
  subtitle: 'subtitle'
};

exports.Prisma.ProductImagesScalarFieldEnum = {
  id: 'id',
  productSlug: 'productSlug',
  color: 'color',
  imgs: 'imgs'
};

exports.Prisma.ProductTranslationScalarFieldEnum = {
  id: 'id',
  productSlug: 'productSlug',
  locale: 'locale',
  name: 'name',
  title: 'title',
  subtitle: 'subtitle'
};

exports.Prisma.ProductItemsScalarFieldEnum = {
  id: 'id',
  productSlug: 'productSlug',
  title: 'title',
  slug: 'slug',
  img: 'img',
  isActive: 'isActive',
  lookupItemId: 'lookupItemId'
};

exports.Prisma.ProductItemsLookupScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  img: 'img',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductItemsTranslationScalarFieldEnum = {
  id: 'id',
  productItemId: 'productItemId',
  locale: 'locale',
  title: 'title',
  subtitle: 'subtitle',
  isActive: 'isActive'
};

exports.Prisma.ProductItemsLookupTranslationScalarFieldEnum = {
  id: 'id',
  lookupItemId: 'lookupItemId',
  locale: 'locale',
  title: 'title',
  subtitle: 'subtitle',
  isActive: 'isActive'
};

exports.Prisma.FeatureScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  img: 'img',
  isActive: 'isActive',
  preview: 'preview',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureTranslationScalarFieldEnum = {
  id: 'id',
  featureId: 'featureId',
  locale: 'locale',
  name: 'name',
  desc: 'desc',
  isActive: 'isActive'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ServiceStatus = exports.$Enums.ServiceStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.Prisma.ModelName = {
  User: 'User',
  UserDetails: 'UserDetails',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  TwoFactor: 'TwoFactor',
  Order: 'Order',
  OrderProduct: 'OrderProduct',
  BenefitDescription: 'BenefitDescription',
  Benefits: 'Benefits',
  Service: 'Service',
  Category: 'Category',
  CategoryTranslation: 'CategoryTranslation',
  Product: 'Product',
  ProductSpecs: 'ProductSpecs',
  ProductImages: 'ProductImages',
  ProductTranslation: 'ProductTranslation',
  ProductItems: 'ProductItems',
  ProductItemsLookup: 'ProductItemsLookup',
  ProductItemsTranslation: 'ProductItemsTranslation',
  ProductItemsLookupTranslation: 'ProductItemsLookupTranslation',
  Feature: 'Feature',
  FeatureTranslation: 'FeatureTranslation'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
